# Generated by Django 4.0.3 on 2022-04-01 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_student_score_alter_student_major'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Email',
            field=models.CharField(max_length=320, unique=True),
        ),
    ]
